
export default interface FieldLayoutType {
  NORMAL: 'NORMAL'
	OUTSIDE: 'OUTSIDE'
	OUTSIDEBELOW: 'OUTSIDEBELOW'
	OUTSIDEABOVE: 'OUTSIDEABOVE'
	STARTROW: 'STARTROW'
	MIDROW: 'MIDROW'
	ENDROW: 'ENDROW'
}

