
export default interface TaskType {
  SCHEDULED_SCRIPT: 'SCHEDULED_SCRIPT'
  MAP_REDUCE: 'MAP_REDUCE'
  CSV_IMPORT:'CSV_IMPORT'
  ENTITY_DEDUPLICATION:'ENTITY_DEDUPLICATION'
  WORKFLOW_TRIGGER:'WORKFLOW_TRIGGER'
  SEARCH:'SEARCH'
  QUERY:'QUERY'
  SUITE_QL:'SUITEQL'
  RECORD_ACTION:'RECORD_ACTION'
  PIVOT:'PIVOT'
  DOCUMENT_CAPTURE:'DOCUMENT_CAPTURE'
}

